#
# ██████╗░██╗░░░██╗  ███████╗███╗░░██╗░█████╗░░█████╗░░██████╗░
# ██╔══██╗╚██╗░██╔╝  ██╔════╝████╗░██║██╔══██╗██╔══██╗██╔════╝░
# ██████╦╝░╚████╔╝░  █████╗░░██╔██╗██║██║░░╚═╝██║░░██║██║░░██╗░
# ██╔══██╗░░╚██╔╝░░  ██╔══╝░░██║╚████║██║░░██╗██║░░██║██║░░╚██╗
# ██████╦╝░░░██║░░░  ███████╗██║░╚███║╚█████╔╝╚█████╔╝╚██████╔╝
# ╚═════╝░░░░╚═╝░░░╚══════╝╚═╝░░╚══╝░╚════╝░░╚════╝░░╚═════╝░
#
# Зачарования
enchantments:
  DIG_SPEED:
    max_level: 10
  DURABILITY:
    max_level: 5
